name: "Terraform CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2
      - id: "auth"
        name: "Authenticate to Google Cloud v1"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/906203989757/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "cicd-superadmin@tf-state-00.iam.gserviceaccount.com"
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.1
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1.1.0"
        with:
          version: ">= 363.0.0"
      - name: Terraform Plan
        run: |
          echo "$(PWD)"
          gcloud auth list
          terraform version
          terraform init
          terraform plan
